// <auto-generated />
using LayoutPlannerPOC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LayoutPlannerPOC.Migrations
{
    [DbContext(typeof(FactoryComponentContext))]
    partial class FactoryComponentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("LayoutPlannerPOC.Data.FactoryComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageFilePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Rotation")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("X")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Y")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("FactoryComponents", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Height = 10,
                            Name = "Constructor",
                            Rotation = 0,
                            Width = 5,
                            X = 10,
                            Y = 0
                        },
                        new
                        {
                            Id = 2,
                            Height = 4,
                            Name = "Smelter",
                            Rotation = 0,
                            Width = 10,
                            X = 15,
                            Y = 5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
